version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - APP_SETTINGS=app.config.DevelopmentConfig